branches:
  only:
    - master

clone_depth: 50

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      GENERATOR: "Visual Studio 12 2013"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Visual Studio 14 2015"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017"

install:
  - cmake --version

  - git clone --branch=4.2.0 --depth=1 --single-branch
    -- https://github.com/WeAreROLI/JUCE.git "%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-4.2.0"
  - git clone --branch=4.3.1 --depth=1 --single-branch
    -- https://github.com/WeAreROLI/JUCE.git "%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-4.3.1"
  - git clone --branch=5.0.0 --depth=1 --single-branch
    -- https://github.com/WeAreROLI/JUCE.git "%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-5.0.0"
  - git clone --branch=5.2.1 --depth=1 --single-branch
    -- https://github.com/WeAreROLI/JUCE.git "%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-5.2.1"
  - git clone --branch=5.3.1 --depth=1 --single-branch
    -- https://github.com/WeAreROLI/JUCE.git "%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-5.3.1"

build_script:
  - mkdir %APPVEYOR_BUILD_FOLDER%\build
  - cd %APPVEYOR_BUILD_FOLDER%\build

  # Configure and build FRUT with JUCE 4.2.0
  - >
    cmake .. -G "%GENERATOR%" -DUSE_CRLF_LINE_ENDINGS=OFF
    -DJUCE_ROOT="%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-4.2.0"
  - cmake --build . --config Debug -- -v:m -maxcpucount

  # Configure and build FRUT with JUCE 4.3.1
  - >
    cmake .. -G "%GENERATOR%" -DUSE_CRLF_LINE_ENDINGS=OFF
    -DJUCE_ROOT="%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-4.3.1"
  - cmake --build . --config Debug -- -v:m -maxcpucount

  # Configure and build FRUT with JUCE 5.0.0
  - >
    cmake .. -G "%GENERATOR%" -DUSE_CRLF_LINE_ENDINGS=OFF
    -DJUCE_ROOT="%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-5.0.0"
  - cmake --build . --config Debug -- -v:m -maxcpucount

  # Configure and build FRUT with JUCE 5.2.1
  - >
    cmake .. -G "%GENERATOR%" -DUSE_CRLF_LINE_ENDINGS=OFF
    -DJUCE_ROOT="%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-5.2.1"
  - cmake --build . --config Debug -- -v:m -maxcpucount

  # Configure and build FRUT with JUCE 5.3.1
  - >
    cmake .. -G "%GENERATOR%" -DUSE_CRLF_LINE_ENDINGS=OFF
    -DJUCE_ROOT="%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-5.3.1"
  - cmake --build . --config Debug -- -v:m -maxcpucount

  # Build and install FRUT in ./prefix
  - cmake .. -DCMAKE_INSTALL_PREFIX="%APPVEYOR_BUILD_FOLDER%/prefix"
  - cmake --build . --config Release --target install -- -v:m -maxcpucount

test_script:
  # Check that generated CMakeLists.txt files are up-to-date
  - cd %APPVEYOR_BUILD_FOLDER%
  - >
    cmake -DJUCE_VERSION="4.2.0"
    -DJucer2Reprojucer_EXE="prefix/FRUT/bin/Jucer2Reprojucer.exe"
    -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
  - >
    cmake -DJUCE_VERSION="4.3.1"
    -DJucer2Reprojucer_EXE="prefix/FRUT/bin/Jucer2Reprojucer.exe"
    -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
  - >
    cmake -DJUCE_VERSION="5.0.0"
    -DJucer2Reprojucer_EXE="prefix/FRUT/bin/Jucer2Reprojucer.exe"
    -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
  - >
    cmake -DJUCE_VERSION="5.2.1"
    -DJucer2Reprojucer_EXE="prefix/FRUT/bin/Jucer2Reprojucer.exe"
    -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
  - >
    cmake -DJUCE_VERSION="5.3.1"
    -DJucer2Reprojucer_EXE="prefix/FRUT/bin/Jucer2Reprojucer.exe"
    -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
  - git diff --quiet

  - mkdir %APPVEYOR_BUILD_FOLDER%\ci\AllJuceProjects\build
  - cd %APPVEYOR_BUILD_FOLDER%\ci\AllJuceProjects\build

  # Configure all JUCE 4.2.0 projects
  - >
    cmake .. -G "%GENERATOR%" -DJUCE_VERSION="4.2.0"
    -DJUCER_AAX_SDK_FOLDER="%APPVEYOR_BUILD_FOLDER%/ci/fake-SDKs/AAX"
    -DJUCER_VST3_SDK_FOLDER="%APPVEYOR_BUILD_FOLDER%/ci/fake-SDKs/VST3"
    -DJUCER_VST_SDK_FOLDER="%APPVEYOR_BUILD_FOLDER%/ci/fake-SDKs/VST"

  # Configure all JUCE 4.3.1 projects
  - >
    cmake .. -G "%GENERATOR%" -DJUCE_VERSION="4.3.1"
    -DJUCER_AAX_SDK_FOLDER="%APPVEYOR_BUILD_FOLDER%/ci/fake-SDKs/AAX"
    -DJUCER_VST3_SDK_FOLDER="%APPVEYOR_BUILD_FOLDER%/ci/fake-SDKs/VST3"

  # Configure all JUCE 5.0.0 projects
  - >
    cmake .. -G "%GENERATOR%" -DJUCE_VERSION="5.0.0"
    -DJUCER_AAX_SDK_FOLDER="%APPVEYOR_BUILD_FOLDER%/ci/fake-SDKs/AAX"
    -DJUCER_VST3_SDK_FOLDER="%APPVEYOR_BUILD_FOLDER%/ci/fake-SDKs/VST3"

  # Configure all JUCE 5.2.1 projects
  - >
    cmake .. -G "%GENERATOR%" -DJUCE_VERSION="5.2.1"
    -DJUCER_AAX_SDK_FOLDER="%APPVEYOR_BUILD_FOLDER%/ci/fake-SDKs/AAX"
    -DJUCER_VST3_SDK_FOLDER="%APPVEYOR_BUILD_FOLDER%/ci/fake-SDKs/VST3"

  # Configure all JUCE 5.3.1 projects
  - >
    cmake .. -G "%GENERATOR%" -DJUCE_VERSION="5.3.1"
    -DJUCER_VST3_SDK_FOLDER="%APPVEYOR_BUILD_FOLDER%/ci/fake-SDKs/VST3"
