branches:
  only:
    - master

clone_depth: 50

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      GENERATOR: "Visual Studio 12 2013"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Visual Studio 14 2015"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017"

install:
  - cmake --version

  - git clone --branch=4.2.0 --depth=1 --single-branch
    -- https://github.com/WeAreROLI/JUCE.git "%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-4.2.0"
  - git clone --branch=4.3.1 --depth=1 --single-branch
    -- https://github.com/WeAreROLI/JUCE.git "%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-4.3.1"
  - git clone --branch=5.0.0 --depth=1 --single-branch
    -- https://github.com/WeAreROLI/JUCE.git "%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-5.0.0"
  - git clone --branch=5.2.0 --depth=1 --single-branch
    -- https://github.com/WeAreROLI/JUCE.git "%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-5.2.0"

build_script:
  # Configure and build FRUT with JUCE 4.2.0
  - mkdir %APPVEYOR_BUILD_FOLDER%\4.2.0_build
  - cd %APPVEYOR_BUILD_FOLDER%\4.2.0_build
  - >
    cmake .. -G "%GENERATOR%"
    -DJUCE_ROOT="%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-4.2.0"
    -DUSE_CRLF_LINE_ENDINGS=OFF
  - cmake --build . --config Debug -- -v:m -maxcpucount

  # Configure and build FRUT with JUCE 4.3.1
  - mkdir %APPVEYOR_BUILD_FOLDER%\4.3.1_build
  - cd %APPVEYOR_BUILD_FOLDER%\4.3.1_build
  - >
    cmake .. -G "%GENERATOR%"
    -DJUCE_ROOT="%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-4.3.1"
    -DUSE_CRLF_LINE_ENDINGS=OFF
  - cmake --build . --config Debug -- -v:m -maxcpucount

  # Configure and build FRUT with JUCE 5.0.0
  - mkdir %APPVEYOR_BUILD_FOLDER%\5.0.0_build
  - cd %APPVEYOR_BUILD_FOLDER%\5.0.0_build
  - >
    cmake .. -G "%GENERATOR%"
    -DJUCE_ROOT="%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-5.0.0"
    -DUSE_CRLF_LINE_ENDINGS=OFF
  - cmake --build . --config Debug -- -v:m -maxcpucount

  # Configure and build FRUT with JUCE 5.2.0
  - mkdir %APPVEYOR_BUILD_FOLDER%\5.2.0_build
  - cd %APPVEYOR_BUILD_FOLDER%\5.2.0_build
  - >
    cmake .. -G "%GENERATOR%"
    -DJUCE_ROOT="%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-5.2.0"
    -DUSE_CRLF_LINE_ENDINGS=OFF
  - cmake --build . --config Debug -- -v:m -maxcpucount

test_script:
  # Check that generated CMakeLists.txt files are up-to-date
  - cd %APPVEYOR_BUILD_FOLDER%
  - >
    cmake -DJUCE_VERSION="4.2.0"
    -DJucer2Reprojucer_EXE="4.2.0_build/Jucer2Reprojucer/Debug/ConsoleApp/Jucer2Reprojucer.exe"
    -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
  - >
    cmake -DJUCE_VERSION="4.3.1"
    -DJucer2Reprojucer_EXE="4.3.1_build/Jucer2Reprojucer/Debug/ConsoleApp/Jucer2Reprojucer.exe"
    -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
  - >
    cmake -DJUCE_VERSION="5.0.0"
    -DJucer2Reprojucer_EXE="5.0.0_build/Jucer2Reprojucer/Debug/ConsoleApp/Jucer2Reprojucer.exe"
    -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
  - >
    cmake -DJUCE_VERSION="5.2.0"
    -DJucer2Reprojucer_EXE="5.2.0_build/Jucer2Reprojucer/Debug/ConsoleApp/Jucer2Reprojucer.exe"
    -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
  - git diff --quiet

  # Configure all JUCE 4.2.0 projects
  - mkdir %APPVEYOR_BUILD_FOLDER%\ci\AllJuceProjects\4.2.0_build
  - cd %APPVEYOR_BUILD_FOLDER%\ci\AllJuceProjects\4.2.0_build
  - cmake .. -G "%GENERATOR%" -DJUCE_VERSION="4.2.0"

  # Configure all JUCE 4.3.1 projects
  - mkdir %APPVEYOR_BUILD_FOLDER%\ci\AllJuceProjects\4.3.1_build
  - cd %APPVEYOR_BUILD_FOLDER%\ci\AllJuceProjects\4.3.1_build
  - cmake .. -G "%GENERATOR%" -DJUCE_VERSION="4.3.1"

  # Configure all JUCE 5.0.0 projects
  - mkdir %APPVEYOR_BUILD_FOLDER%\ci\AllJuceProjects\5.0.0_build
  - cd %APPVEYOR_BUILD_FOLDER%\ci\AllJuceProjects\5.0.0_build
  - cmake .. -G "%GENERATOR%" -DJUCE_VERSION="5.0.0"

  # Configure all JUCE 5.2.0 projects
  - mkdir %APPVEYOR_BUILD_FOLDER%\ci\AllJuceProjects\5.2.0_build
  - cd %APPVEYOR_BUILD_FOLDER%\ci\AllJuceProjects\5.2.0_build
  - cmake .. -G "%GENERATOR%" -DJUCE_VERSION="5.2.0"
