clone_depth: 50

branches:
  only:
    - master

install:
  - cmake --version

  - git clone -q https://github.com/julianstorer/JUCE.git ../JUCE --depth=1

build_script:
  - mkdir examples\build
  - cd examples\build
  - cmake ..
  - cmake --build . --config Debug
  - cmake --build . --config Release
