branches:
  only:
    - master

clone_depth: 50

environment:
  matrix:
    - GENERATOR: "Visual Studio 12 2013"
    - GENERATOR: "Visual Studio 14 2015"

install:
  - cmake --version

  - set JUCE_ROOT="%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE"
  - git clone --depth=10 --quiet -- https://github.com/WeAreROLI/JUCE.git %JUCE_ROOT%
  - cd %JUCE_ROOT%
  - git reset --hard 75cd666a61f31eaa3ee6c6d9ad97bc404878a0d8
  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  # Configure and build BinaryDataBuilder, IconBuilder and Jucer2Reprojucer
  - mkdir %APPVEYOR_BUILD_FOLDER%\ci\ReprojucerHelpers\build
  - cd %APPVEYOR_BUILD_FOLDER%\ci\ReprojucerHelpers\build
  - >
    cmake .. -G "%GENERATOR%"
    -DJUCE_ROOT="%JUCE_ROOT%"
    -DJUCE_modules_DIRS="%JUCE_ROOT%/modules"
    -DProjucer_jucer_FILE="%JUCE_ROOT%/extras/Projucer/Projucer.jucer"
  - cmake --build . --config Debug

  # Check that generated CMakeLists.txt files are up-to-date
  - cd %APPVEYOR_BUILD_FOLDER%
  - >
    cmake
    -DJUCE_ROOT="%JUCE_ROOT%"
    -DJucer2Reprojucer_EXE="ci/ReprojucerHelpers/build/Jucer2Reprojucer/Debug/Jucer2Reprojucer.exe"
    -P Jucer2Reprojucer/generated/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
  - git diff --quiet

  # Configure all JUCE projects
  - mkdir %APPVEYOR_BUILD_FOLDER%\Jucer2Reprojucer\generated\JUCE\build
  - cd %APPVEYOR_BUILD_FOLDER%\Jucer2Reprojucer\generated\JUCE\build
  - >
    cmake .. -G "%GENERATOR%"
    -DJUCE_ROOT="%JUCE_ROOT%"
    -DJUCER_VST3_SDK_FOLDER="%APPVEYOR_BUILD_FOLDER%/ci/third-party/vstsdk366_27_06_2016_build_61/VST3 SDK"

  # Configure and build JUCE's Plugin Host, JuceDemoPlugin and Projucer
  - mkdir %APPVEYOR_BUILD_FOLDER%\ci\JuceProjects\build
  - cd %APPVEYOR_BUILD_FOLDER%\ci\JuceProjects\build
  - >
    cmake .. -G "%GENERATOR%"
    -DJUCER_VST3_SDK_FOLDER="%APPVEYOR_BUILD_FOLDER%/ci/third-party/vstsdk367_03_03_2017_build_352/VST_SDK/VST3_SDK"
    -DJuceDemoPlugin_jucer_FILE="%JUCE_ROOT%/examples/audio plugin demo/JuceDemoPlugin.jucer"
    -DPlugin_Host_jucer_FILE="%JUCE_ROOT%/examples/audio plugin host/Plugin Host.jucer"
    -DProjucer_jucer_FILE="%JUCE_ROOT%/extras/Projucer/Projucer.jucer"
  - cmake --build . --config Debug
