branches:
  only:
    - master

clone_depth: 50

install:
  - cmake --version

  - git clone --branch=4.2.0 --depth=1 --single-branch
    -- https://github.com/WeAreROLI/JUCE.git "%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-4.2.0"
  - git clone --branch=4.3.1 --depth=1 --single-branch
    -- https://github.com/WeAreROLI/JUCE.git "%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-4.3.1"
  - git clone --branch=5.0.0 --depth=1 --single-branch
    -- https://github.com/WeAreROLI/JUCE.git "%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-5.0.0"
  - git clone --branch=5.2.1 --depth=1 --single-branch
    -- https://github.com/WeAreROLI/JUCE.git "%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-5.2.1"
  - git clone --branch=5.3.1 --depth=1 --single-branch
    -- https://github.com/WeAreROLI/JUCE.git "%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-5.3.1"
  - git clone --branch=5.4.3 --depth=1 --single-branch
    -- https://github.com/WeAreROLI/JUCE.git "%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-5.4.3"

  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;%PATH%

build_script:
  - mkdir %APPVEYOR_BUILD_FOLDER%\build_Debug
  - mkdir %APPVEYOR_BUILD_FOLDER%\build_Release

  # Configure and build FRUT with JUCE 4.2.0
  - cd %APPVEYOR_BUILD_FOLDER%\build_Debug
  - >
    cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Debug
    -DJUCE_ROOT="%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-4.2.0"
  - cmake --build . -- -j4
  - cd %APPVEYOR_BUILD_FOLDER%\build_Release
  - >
    cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
    -DJUCE_ROOT="%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-4.2.0"

  # Configure and build FRUT with JUCE 4.3.1
  - cd %APPVEYOR_BUILD_FOLDER%\build_Debug
  - >
    cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Debug
    -DJUCE_ROOT="%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-4.3.1"
  - cmake --build . -- -j4
  - cd %APPVEYOR_BUILD_FOLDER%\build_Release
  - >
    cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
    -DJUCE_ROOT="%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-4.3.1"

  # Configure and build FRUT with JUCE 5.2.1
  - cd %APPVEYOR_BUILD_FOLDER%\build_Debug
  - >
    cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Debug
    -DJUCE_ROOT="%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-5.2.1"
  - cmake --build . -- -j4
  - cd %APPVEYOR_BUILD_FOLDER%\build_Release
  - >
    cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
    -DJUCE_ROOT="%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-5.2.1"

  # Configure and build FRUT with JUCE 5.4.3
  - cd %APPVEYOR_BUILD_FOLDER%\build_Debug
  - >
    cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Debug
    -DJUCE_ROOT="%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-5.4.3"
  - cmake --build . -- -j4
  - cd %APPVEYOR_BUILD_FOLDER%\build_Release
  - >
    cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
    -DJUCE_ROOT="%APPVEYOR_BUILD_FOLDER%/ci/tmp/JUCE-5.4.3"

  # Build and install FRUT in ./prefix
  - cmake .. -DCMAKE_INSTALL_PREFIX="%APPVEYOR_BUILD_FOLDER%/prefix"
  - cmake --build . --target install -- -j4

test_script:
  # Check that generated CMakeLists.txt files are up-to-date
  - cd %APPVEYOR_BUILD_FOLDER%
  - >
    cmake -DJucer2Reprojucer_EXE="prefix/FRUT/bin/Jucer2Reprojucer.exe"
    -P ci/apply-Jucer2Reprojucer-to-test-jucers.cmake
  - >
    cmake -DJUCE_VERSION="4.2.0"
    -DJucer2Reprojucer_EXE="prefix/FRUT/bin/Jucer2Reprojucer.exe"
    -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
  - >
    cmake -DJUCE_VERSION="4.3.1"
    -DJucer2Reprojucer_EXE="prefix/FRUT/bin/Jucer2Reprojucer.exe"
    -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
  - >
    cmake -DJUCE_VERSION="5.0.0"
    -DJucer2Reprojucer_EXE="prefix/FRUT/bin/Jucer2Reprojucer.exe"
    -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
  - >
    cmake -DJUCE_VERSION="5.2.1"
    -DJucer2Reprojucer_EXE="prefix/FRUT/bin/Jucer2Reprojucer.exe"
    -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
  - >
    cmake -DJUCE_VERSION="5.3.1"
    -DJucer2Reprojucer_EXE="prefix/FRUT/bin/Jucer2Reprojucer.exe"
    -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
  - >
    cmake -DJUCE_VERSION="5.4.3"
    -DJucer2Reprojucer_EXE="prefix/FRUT/bin/Jucer2Reprojucer.exe"
    -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
  - git diff --quiet
