clone_depth: 50

branches:
  only:
    - master

install:
  - cmake --version

  - git clone -q https://github.com/julianstorer/JUCE.git ../JUCE --depth=1

build_script:
  - mkdir examples\AudioAppExample\build
  - cd examples\AudioAppExample\build
  - cmake ..
  - cmake --build . --config Debug
  - cmake --build . --config Release

  - cd %APPVEYOR_BUILD_FOLDER%

  - mkdir examples\OSCMonitor\build
  - cd examples\OSCMonitor\build
  - cmake ..
  - cmake --build . --config Debug
  - cmake --build . --config Release
