branches:
  only:
    - master

clone_depth: 50

install:
  - cmake --version

  - git clone --depth=10 --quiet -- https://github.com/WeAreROLI/JUCE.git ../JUCE
  - cd ../JUCE
  - git reset --hard 75cd666a61f31eaa3ee6c6d9ad97bc404878a0d8
  - cd %APPVEYOR_BUILD_FOLDER%

  - mkdir C:\SDKs
  - ps: Invoke-WebRequest -Uri http://www.steinberg.net/sdk_downloads/vstsdk367_03_03_2017_build_352.zip -OutFile C:\SDKs\vstsdk3.zip
  - 7z x C:\SDKs\vstsdk3.zip -oC:\SDKs

build_script:
  - mkdir "examples\audio plugin host\build"
  - cd "examples\audio plugin host\build"
  - cmake ..
  - cmake --build . --config Debug
  - cmake --build . --config Release

  - cd %APPVEYOR_BUILD_FOLDER%

  - mkdir examples\NetworkGraphicsDemo\build
  - cd examples\NetworkGraphicsDemo\build
  - cmake ..
  - cmake --build . --config Debug
  - cmake --build . --config Release

  - cd %APPVEYOR_BUILD_FOLDER%

  - mkdir extras\Projucer\build
  - cd extras\Projucer\build
  - cmake ..
  - cmake --build . --config Debug
  - cmake --build . --config Release

  - cd %APPVEYOR_BUILD_FOLDER%

  - mkdir "examples\audio plugin demo\build"
  - cd "examples\audio plugin demo\build"
  - cmake ..
  - cmake --build . --config Debug
  - cmake --build . --config Release
