branches:
  only:
    - master

clone_depth: 50

install:
  - cmake --version

  - git clone --depth=10 --quiet -- https://github.com/WeAreROLI/JUCE.git ../JUCE
  - cd ../JUCE
  - git reset --hard 75cd666a61f31eaa3ee6c6d9ad97bc404878a0d8
  - cd %APPVEYOR_BUILD_FOLDER%

  - mkdir C:\SDKs\VST_SDK
  - xcopy /S ci\third-party\VST_SDK C:\SDKs\VST_SDK

build_script:
  - mkdir ci\build
  - cd ci\build

  - >
    cmake ..
    -DJUCE_ROOT="../../../JUCE"
    -DJuceDemoPlugin_jucer_FILE="../../../JUCE/examples/audio plugin demo/JuceDemoPlugin.jucer"
    -DNetworkGraphicsDemo_jucer_FILE="../../../JUCE/examples/NetworkGraphicsDemo/NetworkGraphicsDemo.jucer"
    -DPlugin_Host_jucer_FILE="../../../JUCE/examples/audio plugin host/Plugin Host.jucer"
    -DProjucer_jucer_FILE="../../../JUCE/extras/Projucer/Projucer.jucer"

  - cmake --build . --config Debug
  - cmake --build . --config Release
