branches:
  only:
    - master

language: cpp

before_install:
  - export JUCE_ROOT=${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-${JUCE_VERSION}
  - git clone --branch=${JUCE_VERSION} --depth=1 --single-branch -- https://github.com/WeAreROLI/JUCE.git $JUCE_ROOT

install-anchors:
  - &install-linux
    - mkdir -p ${TRAVIS_BUILD_DIR}/ci/tmp/cmake
    - >
      wget --no-check-certificate --output-document=- http://www.cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz
      | tar --extract --gzip --directory=${TRAVIS_BUILD_DIR}/ci/tmp/cmake --strip-components=1
    - export PATH=${TRAVIS_BUILD_DIR}/ci/tmp/cmake/bin:$PATH

  - &install-osx
    - cmake --version

script-anchors:
  - &script-linux
    - set -e

    # Configure and build BinaryDataBuilder, IconBuilder and Jucer2Reprojucer
    - mkdir ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/{Debug_build,Release_build}
    - cd ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/Debug_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Debug
      -DJUCE_ROOT="${JUCE_ROOT}"
      -DJUCE_modules_DIRS="${JUCE_ROOT}/modules"
      -DProjucer_jucer_FILE="${JUCE_ROOT}/extras/Projucer/Projucer.jucer"
    - cmake --build .
    - cd ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/Release_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Release
      -DJUCE_ROOT="${JUCE_ROOT}"
      -DJUCE_modules_DIRS="${JUCE_ROOT}/modules"
      -DProjucer_jucer_FILE="${JUCE_ROOT}/extras/Projucer/Projucer.jucer"

    # Check that generated CMakeLists.txt files are up-to-date
    - cd ${TRAVIS_BUILD_DIR}
    - >
      cmake
      -DJUCE_ROOT="${JUCE_ROOT}"
      -DJucer2Reprojucer_EXE="ci/ReprojucerHelpers/Debug_build/Jucer2Reprojucer/Jucer2Reprojucer"
      -Dgenerated_JUCE_ROOT="Jucer2Reprojucer/generated/JUCE-${JUCE_VERSION}"
      -P Jucer2Reprojucer/generated/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
    - git diff --quiet

    # Configure all JUCE projects
    - mkdir ${TRAVIS_BUILD_DIR}/Jucer2Reprojucer/generated/JUCE-${JUCE_VERSION}/{Debug_build,Release_build}
    - cd ${TRAVIS_BUILD_DIR}/Jucer2Reprojucer/generated/JUCE-${JUCE_VERSION}/Debug_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Debug
      -DJUCE_ROOT="${JUCE_ROOT}"
      -DJUCER_VST_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/third-party/vstsdk366_27_06_2016_build_61/VST3 SDK"
    - cd ${TRAVIS_BUILD_DIR}/Jucer2Reprojucer/generated/JUCE-${JUCE_VERSION}/Release_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Release
      -DJUCE_ROOT="${JUCE_ROOT}"
      -DJUCER_VST_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/third-party/vstsdk366_27_06_2016_build_61/VST3 SDK"

    # Configure and build JUCE's Plugin Host, JuceDemoPlugin and Projucer
    - mkdir ${TRAVIS_BUILD_DIR}/ci/JuceProjects-${JUCE_VERSION}/{Debug_build,Release_build}
    - cd ${TRAVIS_BUILD_DIR}/ci/JuceProjects-${JUCE_VERSION}/Debug_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Debug
      -DJUCER_VST_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/third-party/vstsdk366_27_06_2016_build_61/VST3 SDK"
      -DJuceDemoPlugin_jucer_FILE="${JUCE_ROOT}/examples/audio plugin demo/JuceDemoPlugin.jucer"
      -DPlugin_Host_jucer_FILE="${JUCE_ROOT}/examples/audio plugin host/Plugin Host.jucer"
      -DProjucer_jucer_FILE="${JUCE_ROOT}/extras/Projucer/Projucer.jucer"
    - cmake --build .
    - cd ${TRAVIS_BUILD_DIR}/ci/JuceProjects-${JUCE_VERSION}/Release_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Release
      -DJUCER_VST_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/third-party/vstsdk366_27_06_2016_build_61/VST3 SDK"
      -DJuceDemoPlugin_jucer_FILE="${JUCE_ROOT}/examples/audio plugin demo/JuceDemoPlugin.jucer"
      -DPlugin_Host_jucer_FILE="${JUCE_ROOT}/examples/audio plugin host/Plugin Host.jucer"
      -DProjucer_jucer_FILE="${JUCE_ROOT}/extras/Projucer/Projucer.jucer"

    - set +e

  - &script-osx
    - set -e

    # Configure and build BinaryDataBuilder, IconBuilder and Jucer2Reprojucer
    - mkdir ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/build
    - cd ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/build
    - >
      cmake .. -G Xcode
      -DJUCE_ROOT="${JUCE_ROOT}"
      -DJUCE_modules_DIRS="${JUCE_ROOT}/modules"
      -DProjucer_jucer_FILE="${JUCE_ROOT}/extras/Projucer/Projucer.jucer"
    - cmake --build . --config Debug

    # Check that generated CMakeLists.txt files are up-to-date
    - cd ${TRAVIS_BUILD_DIR}
    - >
      cmake
      -DJUCE_ROOT="${JUCE_ROOT}"
      -DJucer2Reprojucer_EXE="ci/ReprojucerHelpers/build/Jucer2Reprojucer/Debug/Jucer2Reprojucer"
      -Dgenerated_JUCE_ROOT="Jucer2Reprojucer/generated/JUCE-${JUCE_VERSION}"
      -P Jucer2Reprojucer/generated/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
    - git diff --quiet

    # Configure all JUCE projects
    - mkdir ${TRAVIS_BUILD_DIR}/Jucer2Reprojucer/generated/JUCE-${JUCE_VERSION}/build
    - cd ${TRAVIS_BUILD_DIR}/Jucer2Reprojucer/generated/JUCE-${JUCE_VERSION}/build
    - >
      cmake .. -G Xcode
      -DJUCE_ROOT="${JUCE_ROOT}"
      -DJUCER_VST_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/third-party/vstsdk366_27_06_2016_build_61/VST3 SDK"
      -DJUCER_VST3_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/third-party/VST_SDK/VST3_SDK"

    # Configure and build JUCE's Plugin Host, JuceDemoPlugin and Projucer
    - mkdir ${TRAVIS_BUILD_DIR}/ci/JuceProjects-${JUCE_VERSION}/build
    - cd ${TRAVIS_BUILD_DIR}/ci/JuceProjects-${JUCE_VERSION}/build
    - >
      cmake .. -G Xcode
      -DJUCER_VST_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/third-party/vstsdk366_27_06_2016_build_61/VST3 SDK"
      -DJUCER_VST3_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/third-party/vstsdk366_27_06_2016_build_61/VST3 SDK"
      -DJuceDemoPlugin_jucer_FILE="${JUCE_ROOT}/examples/audio plugin demo/JuceDemoPlugin.jucer"
      -DPlugin_Host_jucer_FILE="${JUCE_ROOT}/examples/audio plugin host/Plugin Host.jucer"
      -DProjucer_jucer_FILE="${JUCE_ROOT}/extras/Projucer/Projucer.jucer"
    - cmake --build . --config Debug

    - set +e

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      env: JUCE_VERSION=4.2.0
      addons: &addons-linux
        apt:
          packages:
            - libasound2-dev
            - libgl1-mesa-dev
            - libxcursor-dev
            - libxinerama-dev
            - libxrandr-dev
      install: *install-linux
      script: *script-linux

    - os: linux
      dist: trusty
      sudo: false
      env: JUCE_VERSION=4.3.1
      addons: *addons-linux
      install: *install-linux
      script: *script-linux

    - os: osx
      env: JUCE_VERSION=4.2.0
      install: *install-osx
      script: *script-osx

    - os: osx
      env: JUCE_VERSION=4.3.1
      install: *install-osx
      script: *script-osx
