branches:
  only:
    - master

language: cpp

install:
  - cmake --version

  - git clone --branch=4.2.0 --depth=1 --single-branch
    -- https://github.com/WeAreROLI/JUCE.git "${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.2.0"
  - git clone --branch=4.3.1 --depth=1 --single-branch
    -- https://github.com/WeAreROLI/JUCE.git "${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.3.1"
  - git clone --branch=5.0.0 --depth=1 --single-branch
    -- https://github.com/WeAreROLI/JUCE.git "${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.0.0"
  - git clone --branch=5.2.1 --depth=1 --single-branch
    -- https://github.com/WeAreROLI/JUCE.git "${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.2.1"

script-anchors:
  - &script-Makefiles
    # Configure and build FRUT with JUCE 4.2.0
    - mkdir ${TRAVIS_BUILD_DIR}/Debug_4.2.0_build
    - cd ${TRAVIS_BUILD_DIR}/Debug_4.2.0_build
    - cmake .. -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.2.0" -DCMAKE_BUILD_TYPE=Debug
    - cmake --build .
    - mkdir ${TRAVIS_BUILD_DIR}/Release_4.2.0_build
    - cd ${TRAVIS_BUILD_DIR}/Release_4.2.0_build
    - cmake .. -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.2.0" -DCMAKE_BUILD_TYPE=Release

    # Configure and build FRUT with JUCE 4.3.1
    - mkdir ${TRAVIS_BUILD_DIR}/Debug_4.3.1_build
    - cd ${TRAVIS_BUILD_DIR}/Debug_4.3.1_build
    - cmake .. -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.3.1" -DCMAKE_BUILD_TYPE=Debug
    - cmake --build .
    - mkdir ${TRAVIS_BUILD_DIR}/Release_4.3.1_build
    - cd ${TRAVIS_BUILD_DIR}/Release_4.3.1_build
    - cmake .. -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.3.1" -DCMAKE_BUILD_TYPE=Release

    # Configure and build FRUT with JUCE 5.0.0
    - mkdir ${TRAVIS_BUILD_DIR}/Debug_5.0.0_build
    - cd ${TRAVIS_BUILD_DIR}/Debug_5.0.0_build
    - cmake .. -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.0.0" -DCMAKE_BUILD_TYPE=Debug
    - cmake --build .
    - mkdir ${TRAVIS_BUILD_DIR}/Release_5.0.0_build
    - cd ${TRAVIS_BUILD_DIR}/Release_5.0.0_build
    - cmake .. -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.0.0" -DCMAKE_BUILD_TYPE=Release

    # Configure and build FRUT with JUCE 5.2.1
    - mkdir ${TRAVIS_BUILD_DIR}/Debug_5.2.1_build
    - cd ${TRAVIS_BUILD_DIR}/Debug_5.2.1_build
    - cmake .. -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.2.1" -DCMAKE_BUILD_TYPE=Debug
    - cmake --build .
    - mkdir ${TRAVIS_BUILD_DIR}/Release_5.2.1_build
    - cd ${TRAVIS_BUILD_DIR}/Release_5.2.1_build
    - cmake .. -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.2.1" -DCMAKE_BUILD_TYPE=Release

    # Build and install FRUT in ./prefix
    - cmake .. -DCMAKE_INSTALL_PREFIX="${TRAVIS_BUILD_DIR}/prefix"
    - cmake --build . --target install

    # Check that generated CMakeLists.txt files are up-to-date
    - cd ${TRAVIS_BUILD_DIR}
    - >
      cmake -DJUCE_VERSION="4.2.0"
      -DJucer2Reprojucer_EXE="prefix/FRUT/bin/Jucer2Reprojucer"
      -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
    - >
      cmake -DJUCE_VERSION="4.3.1"
      -DJucer2Reprojucer_EXE="prefix/FRUT/bin/Jucer2Reprojucer"
      -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
    - >
      cmake -DJUCE_VERSION="5.0.0"
      -DJucer2Reprojucer_EXE="prefix/FRUT/bin/Jucer2Reprojucer"
      -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
    - >
      cmake -DJUCE_VERSION="5.2.1"
      -DJucer2Reprojucer_EXE="prefix/FRUT/bin/Jucer2Reprojucer"
      -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
    - git diff --quiet

    # Configure all JUCE 4.2.0 projects
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_4.2.0_build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_4.2.0_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Debug -DJUCE_VERSION="4.2.0"
      -DJUCER_AAX_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/AAX"
      -DJUCER_VST_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/VST"
      -DJUCER_VST3_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/VST3"
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_4.2.0_build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_4.2.0_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Release -DJUCE_VERSION="4.2.0"
      -DJUCER_AAX_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/AAX"
      -DJUCER_VST_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/VST"
      -DJUCER_VST3_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/VST3"

    # Configure all JUCE 4.3.1 projects
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_4.3.1_build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_4.3.1_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Debug -DJUCE_VERSION="4.3.1"
      -DJUCER_AAX_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/AAX"
      -DJUCER_VST3_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/VST3"
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_4.3.1_build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_4.3.1_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Release -DJUCE_VERSION="4.3.1"
      -DJUCER_AAX_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/AAX"
      -DJUCER_VST3_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/VST3"

    # Configure all JUCE 5.0.0 projects
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_5.0.0_build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_5.0.0_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Debug -DJUCE_VERSION="5.0.0"
      -DJUCER_AAX_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/AAX"
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_5.0.0_build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_5.0.0_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Release -DJUCE_VERSION="5.0.0"
      -DJUCER_AAX_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/AAX"

    # Configure all JUCE 5.2.1 projects
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_5.2.1_build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_5.2.1_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Debug -DJUCE_VERSION="5.2.1"
      -DJUCER_AAX_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/AAX"
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_5.2.1_build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_5.2.1_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Release -DJUCE_VERSION="5.2.1"
      -DJUCER_AAX_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/AAX"

  - &script-Xcode
    # Configure and build FRUT with JUCE 4.2.0
    - mkdir ${TRAVIS_BUILD_DIR}/4.2.0_build
    - cd ${TRAVIS_BUILD_DIR}/4.2.0_build
    - cmake .. -G Xcode -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.2.0"
    - cmake --build . --config Debug

    # Configure and build FRUT with JUCE 4.3.1
    - mkdir ${TRAVIS_BUILD_DIR}/4.3.1_build
    - cd ${TRAVIS_BUILD_DIR}/4.3.1_build
    - cmake .. -G Xcode -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-4.3.1"
    - cmake --build . --config Debug

    # Configure and build FRUT with JUCE 5.0.0
    - mkdir ${TRAVIS_BUILD_DIR}/5.0.0_build
    - cd ${TRAVIS_BUILD_DIR}/5.0.0_build
    - cmake .. -G Xcode -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.0.0"
    - cmake --build . --config Debug

    # Configure and build FRUT with JUCE 5.2.1
    - mkdir ${TRAVIS_BUILD_DIR}/5.2.1_build
    - cd ${TRAVIS_BUILD_DIR}/5.2.1_build
    - cmake .. -G Xcode -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-5.2.1"
    - cmake --build . --config Debug

    # Build and install FRUT in ./prefix
    - cmake .. -DCMAKE_INSTALL_PREFIX="${TRAVIS_BUILD_DIR}/prefix"
    - cmake --build . --config Release --target install

    # Check that generated CMakeLists.txt files are up-to-date
    - cd ${TRAVIS_BUILD_DIR}
    - >
      cmake -DJUCE_VERSION="4.2.0"
      -DJucer2Reprojucer_EXE="prefix/FRUT/bin/Jucer2Reprojucer"
      -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
    - >
      cmake -DJUCE_VERSION="4.3.1"
      -DJucer2Reprojucer_EXE="prefix/FRUT/bin/Jucer2Reprojucer"
      -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
    - >
      cmake -DJUCE_VERSION="5.0.0"
      -DJucer2Reprojucer_EXE="prefix/FRUT/bin/Jucer2Reprojucer"
      -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
    - >
      cmake -DJUCE_VERSION="5.2.1"
      -DJucer2Reprojucer_EXE="prefix/FRUT/bin/Jucer2Reprojucer"
      -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
    - git diff --quiet

    # Configure all JUCE 4.2.0 projects
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/4.2.0_build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/4.2.0_build
    - >
      cmake .. -G Xcode -DJUCE_VERSION="4.2.0"
      -DJUCER_AAX_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/AAX"
      -DJUCER_VST_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/VST"
      -DJUCER_VST3_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/VST3"

    # Configure all JUCE 4.3.1 projects
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/4.3.1_build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/4.3.1_build
    - >
      cmake .. -G Xcode -DJUCE_VERSION="4.3.1"
      -DJUCER_AAX_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/AAX"
      -DJUCER_VST3_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/VST3"

    # Configure all JUCE 5.0.0 projects
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/5.0.0_build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/5.0.0_build
    - >
      cmake .. -G Xcode -DJUCE_VERSION="5.0.0"
      -DJUCER_AAX_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/AAX"

    # Configure all JUCE 5.2.1 projects
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/5.2.1_build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/5.2.1_build
    - >
      cmake .. -G Xcode -DJUCE_VERSION="5.2.1"
      -DJUCER_AAX_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/fake-SDKs/AAX"

matrix:
  include:
    - os: linux
      services:
        - docker
      before_install:
        - docker build --tag mcmartin/frut - < ci/ubuntu-xenial.dockerfile
        - |
          function cmake {
            docker run --rm -v "${TRAVIS_BUILD_DIR}":"${TRAVIS_BUILD_DIR}" -w "$PWD" mcmartin/frut /usr/bin/cmake $@
          }
      script: *script-Makefiles

    - os: osx
      env: GENERATOR=Makefiles
      script: *script-Makefiles

    - os: osx
      env: GENERATOR=Xcode
      osx_image: xcode9.4
      script: *script-Xcode
