branches:
  only:
    - master

language: cpp

before_install:
  - git clone --branch=${JUCE_VERSION} --depth=1 --single-branch
    -- https://github.com/WeAreROLI/JUCE.git "${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-${JUCE_VERSION}"

install-anchors:
  - &install-linux
    - mkdir -p ${TRAVIS_BUILD_DIR}/ci/tmp/cmake
    - >
      wget --no-check-certificate --output-document=- http://www.cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz
      | tar --extract --gzip --directory=${TRAVIS_BUILD_DIR}/ci/tmp/cmake --strip-components=1
    - export PATH=${TRAVIS_BUILD_DIR}/ci/tmp/cmake/bin:$PATH

  - &install-osx
    - cmake --version

script-anchors:
  - &script-Makefiles
    - set -e

    # Configure and build BinaryDataBuilder, IconBuilder and Jucer2Reprojucer
    - mkdir ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/Debug_build
    - cd ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/Debug_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Debug
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-${JUCE_VERSION}"
      -DJUCE_modules_DIRS="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-${JUCE_VERSION}/modules"
    - cmake --build .
    - mkdir ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/Release_build
    - cd ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/Release_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Release
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-${JUCE_VERSION}"
      -DJUCE_modules_DIRS="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-${JUCE_VERSION}/modules"

    # Check that generated CMakeLists.txt files are up-to-date
    - cd ${TRAVIS_BUILD_DIR}
    - >
      cmake
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-${JUCE_VERSION}"
      -DJucer2Reprojucer_EXE="ci/ReprojucerHelpers/Debug_build/Jucer2Reprojucer/Jucer2Reprojucer"
      -Dgenerated_JUCE_ROOT="Jucer2Reprojucer/generated/JUCE-${JUCE_VERSION}"
      -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
    - git diff --quiet

    # Configure all JUCE projects
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Debug_build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DJUCE_VERSION="${JUCE_VERSION}"
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/Release_build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DJUCE_VERSION="${JUCE_VERSION}"

    - set +e

  - &script-Xcode
    - set -e

    # Configure and build BinaryDataBuilder, IconBuilder and Jucer2Reprojucer
    - mkdir ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/build
    - cd ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/build
    - >
      cmake .. -G Xcode
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-${JUCE_VERSION}"
      -DJUCE_modules_DIRS="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-${JUCE_VERSION}/modules"
    - cmake --build . --config Debug

    # Check that generated CMakeLists.txt files are up-to-date
    - cd ${TRAVIS_BUILD_DIR}
    - >
      cmake
      -DJUCE_ROOT="${TRAVIS_BUILD_DIR}/ci/tmp/JUCE-${JUCE_VERSION}"
      -DJucer2Reprojucer_EXE="ci/ReprojucerHelpers/build/Jucer2Reprojucer/Debug/Jucer2Reprojucer"
      -Dgenerated_JUCE_ROOT="Jucer2Reprojucer/generated/JUCE-${JUCE_VERSION}"
      -P ci/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
    - git diff --quiet

    # Configure all JUCE projects
    - mkdir ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/build
    - cd ${TRAVIS_BUILD_DIR}/ci/AllJuceProjects/build
    - cmake .. -G Xcode -DJUCE_VERSION="${JUCE_VERSION}"

    - set +e

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      env: JUCE_VERSION=4.2.0
      addons: &addons-linux
        apt:
          packages:
            - libasound2-dev
            - libgl1-mesa-dev
            - libxcursor-dev
            - libxinerama-dev
            - libxrandr-dev
      install: *install-linux
      script: *script-Makefiles

    - os: linux
      dist: trusty
      sudo: false
      env: JUCE_VERSION=4.3.1
      addons: *addons-linux
      install: *install-linux
      script: *script-Makefiles

    - os: osx
      env: JUCE_VERSION=4.2.0 GENERATOR=Makefiles
      install: *install-osx
      script: *script-Makefiles

    - os: osx
      env: JUCE_VERSION=4.3.1 GENERATOR=Makefiles
      install: *install-osx
      script: *script-Makefiles

    - os: osx
      env: JUCE_VERSION=4.2.0 GENERATOR=Xcode
      install: *install-osx
      script: *script-Xcode

    - os: osx
      env: JUCE_VERSION=4.3.1 GENERATOR=Xcode
      install: *install-osx
      script: *script-Xcode
