branches:
  only:
    - master

os: osx

install:
  - cmake --version

  - git clone --depth=10 --quiet -- https://github.com/WeAreROLI/JUCE.git ../JUCE
  - cd ../JUCE
  - git reset --hard 75cd666a61f31eaa3ee6c6d9ad97bc404878a0d8
  - cd $TRAVIS_BUILD_DIR

  - mkdir ~/SDKs
  - cp -R ci/third-party/VST_SDK ~/SDKs

script:
  - mkdir ci/build
  - cd ci/build

  - >
    cmake .. -G Xcode
    -DJUCE_ROOT="../../../JUCE"
    -DJuceDemoPlugin_jucer_FILE="../../../JUCE/examples/audio plugin demo/JuceDemoPlugin.jucer"
    -DNetworkGraphicsDemo_jucer_FILE="../../../JUCE/examples/NetworkGraphicsDemo/NetworkGraphicsDemo.jucer"
    -DPlugin_Host_jucer_FILE="../../../JUCE/examples/audio plugin host/Plugin Host.jucer"
    -DProjucer_jucer_FILE="../../../JUCE/extras/Projucer/Projucer.jucer"

  - cmake --build . --config Debug
  - cmake --build . --config Release
