os: osx

branches:
  only:
    - master

install:
  - cmake --version

  - git clone -q https://github.com/julianstorer/JUCE.git ../JUCE --depth=1

script:
  - mkdir examples/AudioAppExample/build
  - cd examples/AudioAppExample/build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - cmake --build .
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build .

  - cd $TRAVIS_BUILD_DIR

  - mkdir examples/NetworkGraphicsDemo/build
  - cd examples/NetworkGraphicsDemo/build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - cmake --build .
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
