branches:
  only:
    - master

language: cpp

before_install:
  - export JUCE_ROOT=${TRAVIS_BUILD_DIR}/ci/tmp/JUCE
  - git clone --depth=10 --quiet -- https://github.com/WeAreROLI/JUCE.git $JUCE_ROOT
  - cd $JUCE_ROOT
  - git reset --hard 75cd666a61f31eaa3ee6c6d9ad97bc404878a0d8
  - cd $TRAVIS_BUILD_DIR

install-anchors:
  - &install-linux
    - mkdir -p ${TRAVIS_BUILD_DIR}/ci/tmp/cmake
    - >
      wget --no-check-certificate --output-document=- http://www.cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz
      | tar --extract --gzip --directory=${TRAVIS_BUILD_DIR}/ci/tmp/cmake --strip-components=1
    - export PATH=${TRAVIS_BUILD_DIR}/ci/tmp/cmake/bin:$PATH

  - &install-osx
    - cmake --version

script-anchors:
  - &script-linux
    - set -e

    - mkdir ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/Debug_build
    - cd ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/Debug_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Debug
      -DJUCE_ROOT="${JUCE_ROOT}"
      -DJUCE_modules_DIRS="${JUCE_ROOT}/modules"
      -DProjucer_jucer_FILE="${JUCE_ROOT}/extras/Projucer/Projucer.jucer"
    - cmake --build .

    - mkdir ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/Release_build
    - cd ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/Release_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Release
      -DJUCE_ROOT="${JUCE_ROOT}"
      -DJUCE_modules_DIRS="${JUCE_ROOT}/modules"
      -DProjucer_jucer_FILE="${JUCE_ROOT}/extras/Projucer/Projucer.jucer"
    - cmake --build .

    - cd ${TRAVIS_BUILD_DIR}
    - >
      cmake
      -DJUCE_ROOT="${JUCE_ROOT}"
      -DJucer2Reprojucer_EXE="ci/ReprojucerHelpers/Debug_build/Jucer2Reprojucer/Jucer2Reprojucer"
      -P Jucer2Reprojucer/generated/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
    - git diff --quiet

    - mkdir ${TRAVIS_BUILD_DIR}/ci/JuceProjects/Debug_build
    - cd ${TRAVIS_BUILD_DIR}/ci/JuceProjects/Debug_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Debug
      -DJuceDemoPlugin_jucer_FILE="${JUCE_ROOT}/examples/audio plugin demo/JuceDemoPlugin.jucer"
      -DPlugin_Host_jucer_FILE="${JUCE_ROOT}/examples/audio plugin host/Plugin Host.jucer"
      -DProjucer_jucer_FILE="${JUCE_ROOT}/extras/Projucer/Projucer.jucer"
    - cmake --build .

    - mkdir ${TRAVIS_BUILD_DIR}/ci/JuceProjects/Release_build
    - cd ${TRAVIS_BUILD_DIR}/ci/JuceProjects/Release_build
    - >
      cmake .. -DCMAKE_BUILD_TYPE=Release
      -DJuceDemoPlugin_jucer_FILE="${JUCE_ROOT}/examples/audio plugin demo/JuceDemoPlugin.jucer"
      -DPlugin_Host_jucer_FILE="${JUCE_ROOT}/examples/audio plugin host/Plugin Host.jucer"
      -DProjucer_jucer_FILE="${JUCE_ROOT}/extras/Projucer/Projucer.jucer"
    - cmake --build .

    - set +e

  - &script-osx
    - set -e

    - mkdir ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/build
    - cd ${TRAVIS_BUILD_DIR}/ci/ReprojucerHelpers/build
    - >
      cmake .. -G Xcode
      -DJUCE_ROOT="${JUCE_ROOT}"
      -DJUCE_modules_DIRS="${JUCE_ROOT}/modules"
      -DProjucer_jucer_FILE="${JUCE_ROOT}/extras/Projucer/Projucer.jucer"
    - cmake --build . --config Debug
    - cmake --build . --config Release

    - cd ${TRAVIS_BUILD_DIR}
    - >
      cmake
      -DJUCE_ROOT="${JUCE_ROOT}"
      -DJucer2Reprojucer_EXE="ci/ReprojucerHelpers/build/Jucer2Reprojucer/Debug/Jucer2Reprojucer"
      -P Jucer2Reprojucer/generated/apply-Jucer2Reprojucer-to-JUCE-jucers.cmake
    - git diff --quiet

    - mkdir ${TRAVIS_BUILD_DIR}/ci/JuceProjects/build
    - cd ${TRAVIS_BUILD_DIR}/ci/JuceProjects/build
    - >
      cmake .. -G Xcode
      -DJUCER_VST3_SDK_FOLDER="${TRAVIS_BUILD_DIR}/ci/third-party/VST_SDK/VST3_SDK"
      -DJuceDemoPlugin_jucer_FILE="${JUCE_ROOT}/examples/audio plugin demo/JuceDemoPlugin.jucer"
      -DPlugin_Host_jucer_FILE="${JUCE_ROOT}/examples/audio plugin host/Plugin Host.jucer"
      -DProjucer_jucer_FILE="${JUCE_ROOT}/extras/Projucer/Projucer.jucer"
    - cmake --build . --config Debug
    - cmake --build . --config Release

    - set +e

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          packages:
            - libasound2-dev
            - libgl1-mesa-dev
            - libxcursor-dev
            - libxinerama-dev
            - libxrandr-dev
      install: *install-linux
      script: *script-linux

    - os: osx
      install: *install-osx
      script: *script-osx
